# Minimal Netlify configuration for the RecordCrate monorepo
# Build the app from the RecordCrate subfolder and publish the dist output there.
[build]
  # run the build using npm in the RecordCrate folder
  command = "npm --prefix RecordCrate run build"
  # publish the Vite output from the subfolder
  publish = "RecordCrate/dist"

# If you need to force a Node version, set it here under build.environment
[build.environment]
  NODE_VERSION = "18"
